baseURL = "https://danapp.app/"
languageCode = "en-us"
author = "Dan Appel"
description = "Blog and homepage"
title = "Dan Appel"
enableEmoji = true
theme = "pixyll"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
# search_engine = true
# google_analytics_id = ""
  twitter_username = "dan_appel"
  github_username = "danappelxx"
  linkedin_username = "dvappel"
  email = "dan@danapp.app"
