baseURL = "https://danapp.app/"
languageCode = "en-us"
author = "Dan Appel"
description = "Dan Appel's blog and homepage"
title = "Dan Appel"
enableEmoji = true
theme = "pixyll"

[params]
# search_engine = true
  twitter_username = "dan_appel"
  github_username = "danappelxx"
  linkedin_username = "dvappel"
  email = "dan@danapp.app"
